### ISSUE TITLE
Сreating aliases doesn't work 

### ISSUE THREAD

**Issue by aisviper** [jconsoli/brcdapi#1]
from brcdapi.zone import create_aliases
from brcdapi import pyfos_auth

session = pyfos_auth.login("admin", "1234567", "1.1.1.1")
print(session)
my_alias_list = [
        {'name': 'a_test1', 'members': ['50:0c:00:11:0d:bb:42:00']},
        {'name': 'a_test2', 'members': ['50:0c:00:11:0d:bb:42:01']},
    ]
create_aliases(session, 2, my_alias_list)
pyfos_auth.logout(session)

backup@vm-test:~/apiiii$ ./apiii.py 
{'_raw_data': {'status': 415, 'reason': 'Unsupported Media'}, 'content-type': 'application/yang-data+xml', 'content-version': None, 'conn': <http.client.HTTPConnection object at 0x7f1ebc9cd3d0>, 'credential': {'User-Agent': 'Rest-Conf', 'Accept': 'application/yang-data+json', 'Content-Type': 'application/yang-data+json', 'Authorization': None}, 'ip_addr': '1.1.1.1', 'ishttps': 'none', 'debug': False}
Traceback (most recent call last):
  File "./apiii.py", line 13, in <module>
    pyfos_auth.logout(session)
  File "/home/backup/apiiii/brcdapi/pyfos_auth.py", line 337, in logout
    conn.request('POST', LOGOUT_RESTCONF, '', session.get('credential'))
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1266, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python3.8/http/client.py", line 1092, in putrequest
    raise CannotSendRequest(self.__state)
http.client.CannotSendRequest: Request-started

**Comment by jconsoli** [comment]
This should be fixed now.
